/**
 * Operational analytics derived from report activity, validated incidents,
 * mobile case resolutions, and current barangay personnel coverage.
 */
import { useMemo, useState } from 'react'
import BarangayOperationalAnalytics from '../components/BarangayOperationalAnalytics'
import { AnalyticsContentSkeleton } from '../components/LoadingSkeleton'
import { usePersonnelContext } from '../context/usePersonnelContext'
import {
  BARANGAY_ANALYTICS_PERIODS,
  BASELINE_REQUIRED_PERSONNEL,
  buildBarangayAnalytics,
} from '../utils/barangayAnalytics'

const toCsvValue = (value) => {
  const rawValue = String(value ?? '')
  const safeValue = typeof value === 'string' && /^[\t\r ]*[=+\-@]/.test(rawValue)
    ? `'${rawValue}`
    : rawValue
  return `"${safeValue.replace(/"/g, '""')}"`
}

const formatDateTime = (isoValue) => {
  if (!isoValue) return '-'

  return new Intl.DateTimeFormat('en-PH', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  }).format(new Date(isoValue))
}

const barangayFromArea = (area = '') => {
  const firstPart = String(area).split(',')[0].trim()
  return firstPart
    .replace(/^barangay\s+/i, '')
    .split(/public|market|zone|route|road|checkpoint|perimeter/i)[0]
    .trim() || firstPart || 'Unspecified'
}

function AnalyticsPage() {
  const [barangayPeriod, setBarangayPeriod] = useState('weekly')
  const { deployments, personnel, reports, isInitialDataLoading } = usePersonnelContext()
  const deploymentCoverage = useMemo(() => {
    const personnelById = new Map(personnel.map((member) => [member.id, member]))
    const coverageByBarangay = new Map()

    deployments.forEach((deployment) => {
      const barangay = barangayFromArea(deployment.patrolArea)
      const current = coverageByBarangay.get(barangay) || {
        barangay,
        assignedPersonnel: 0,
        availablePersonnel: 0,
        requiredPersonnel: BASELINE_REQUIRED_PERSONNEL,
      }
      const member = personnelById.get(deployment.personnelId)
      current.assignedPersonnel += 1
      if (member && member.status !== 'Off Duty') current.availablePersonnel += 1
      coverageByBarangay.set(barangay, current)
    })

    return [...coverageByBarangay.values()]
  }, [deployments, personnel])
  const barangayAnalytics = useMemo(
    () => buildBarangayAnalytics({
      reports,
      deploymentCoverage,
      period: barangayPeriod,
    }),
    [barangayPeriod, deploymentCoverage, reports],
  )
  const highestPriorityBarangay = barangayAnalytics.barangays[0]
  const operationalStats = [
    {
      label: 'Submitted Reports',
      value: barangayAnalytics.totalReports,
      subtext: barangayAnalytics.periodLabel,
    },
    {
      label: 'Validated Incidents',
      value: barangayAnalytics.totalValidatedIncidents,
      subtext: 'Confirmed incident reports',
    },
    {
      label: 'Resolved Cases',
      value: barangayAnalytics.totalResolvedCases,
      subtext: `Of ${barangayAnalytics.totalIncidentReports} submitted incidents`,
      isLive: true,
    },
    {
      label: 'High-Priority Barangays',
      value: barangayAnalytics.highPriorityBarangays,
      subtext: highestPriorityBarangay
        ? `Highest: ${highestPriorityBarangay.barangay}`
        : 'No priority area',
    },
  ]

  const handleGenerateAnalyticsReport = () => {
    const generatedAtIso = new Date().toISOString()

    const csvRows = [
      ['Generated At', formatDateTime(generatedAtIso)],
      ['Generated By', 'Supervisor'],
      [],
      [`Operational Analytics Summary - ${barangayAnalytics.periodLabel}`],
      ['Metric', 'Value'],
      ...operationalStats.map((item) => [item.label, item.value]),
      [],
      [`Barangay Operational Analytics - ${barangayAnalytics.periodLabel}`],
      [
        'Barangay',
        'Submitted Reports',
        'Validated Incidents',
        'Priority Score',
        'Priority Level',
        'Average Severity',
        'Repeat Location',
        'Peak Time',
        'Available Personnel',
        'Required Personnel',
      ],
      ...barangayAnalytics.barangays.map((barangay) => [
        barangay.barangay,
        barangay.reportCount,
        barangay.validatedIncidentCount,
        barangay.priorityScore,
        barangay.priorityLevel,
        barangay.averageSeverity,
        barangay.topLocation || '-',
        barangay.peakTimeWindow || '-',
        barangay.availablePersonnel,
        barangay.requiredPersonnel,
      ]),
    ]

    const csvContent = csvRows
      .map((row) => (row.length === 0 ? '' : row.map(toCsvValue).join(',')))
      .join('\n')

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
    const url = URL.createObjectURL(blob)
    const downloadAnchor = document.createElement('a')
    const fileStamp = generatedAtIso.replace(/[-:TZ]/g, '').slice(0, 14)

    downloadAnchor.href = url
    downloadAnchor.download = `bantaycabagan-analytics-${fileStamp}.csv`
    document.body.appendChild(downloadAnchor)
    downloadAnchor.click()
    document.body.removeChild(downloadAnchor)
    window.setTimeout(() => URL.revokeObjectURL(url), 1000)
  }

  return (
    <div className="page-container fade-in p-3 p-md-4">
      <header className="page-header mb-4 reports-header">
        <div>
          <h2 className="page-title">Analytics</h2>
          <p className="page-subtitle">Patrol, incident, and barangay deployment trends</p>
        </div>
        <div className="analytics-page-actions">
          <div
            className="analytics-segmented-control smooth-underline-control"
            aria-label="Analytics period"
            style={{
              '--smooth-underline-left': `${((BARANGAY_ANALYTICS_PERIODS.findIndex((option) => option.value === barangayPeriod) + 0.5) / BARANGAY_ANALYTICS_PERIODS.length) * 100}%`,
            }}
          >
            {BARANGAY_ANALYTICS_PERIODS.map((option) => (
              <button
                key={option.value}
                type="button"
                className={barangayPeriod === option.value ? 'is-active' : ''}
                onClick={() => setBarangayPeriod(option.value)}
                aria-pressed={barangayPeriod === option.value}
              >
                {option.label}
              </button>
            ))}
          </div>
          <button type="button" className="report-generate-btn" onClick={handleGenerateAnalyticsReport}>
            Generate Report
          </button>
        </div>
      </header>

      {isInitialDataLoading ? <AnalyticsContentSkeleton /> : (
      <>
      <div className="stats-grid analytics-stats-grid row g-3 mb-3 mx-0">
        {operationalStats.map((stat) => (
          <div key={stat.label} className="col-12 col-sm-6 col-xl-3">
            <div className="stat-card slide-up h-100">
              <div className="stat-card__heading">
                <p className="stat-card__label">{stat.label}</p>
                {stat.isLive && (
                  <span className="stat-card__live" title="Synced from mobile resolve updates">
                    <span aria-hidden="true" />
                    Live
                  </span>
                )}
              </div>
              <strong className="stat-card__value">{stat.value}</strong>
              <p className="stat-card__subtext">{stat.subtext}</p>
            </div>
          </div>
        ))}
      </div>

      <BarangayOperationalAnalytics
        analytics={barangayAnalytics}
        period={barangayPeriod}
      />
      </>
      )}
    </div>
  )
}

export default AnalyticsPage
