/**
 * Operational analytics derived from report activity, validated incidents,
 * mobile case resolutions, and current barangay personnel coverage.
 */
import { useMemo, useState } from 'react'
import BarangayOperationalAnalytics from '../components/BarangayOperationalAnalytics'
import { usePersonnelContext } from '../context/usePersonnelContext'
import {
  BARANGAY_DEPLOYMENT_COVERAGE,
} from '../data/reportRecords'
import {
  BARANGAY_ANALYTICS_PERIODS,
  buildBarangayAnalytics,
} from '../utils/barangayAnalytics'

const toCsvValue = (value) => `"${String(value ?? '').replace(/"/g, '""')}"`

const formatDateTime = (isoValue) => {
  if (!isoValue) return '-'

  return new Intl.DateTimeFormat('en-PH', {
    month: 'short',
    day: 'numeric',
    year: 'numeric',
    hour: 'numeric',
    minute: '2-digit',
  }).format(new Date(isoValue))
}

function AnalyticsPage() {
  const [barangayPeriod, setBarangayPeriod] = useState('weekly')
  const { reports } = usePersonnelContext()
  const barangayAnalytics = useMemo(
    () => buildBarangayAnalytics({
      reports,
      deploymentCoverage: BARANGAY_DEPLOYMENT_COVERAGE,
      period: barangayPeriod,
    }),
    [barangayPeriod, reports],
  )
  const highestPriorityBarangay = barangayAnalytics.barangays[0]
  const operationalStats = [
    {
      label: 'Submitted Reports',
      value: barangayAnalytics.totalReports,
      subtext: barangayAnalytics.periodLabel,
    },
    {
      label: 'Validated Incidents',
      value: barangayAnalytics.totalValidatedIncidents,
      subtext: 'Confirmed incident reports',
    },
    {
      label: 'Resolved Cases',
      value: barangayAnalytics.totalResolvedCases,
      subtext: `Of ${barangayAnalytics.totalIncidentReports} submitted incidents`,
      isLive: true,
    },
    {
      label: 'High-Priority Barangays',
      value: barangayAnalytics.highPriorityBarangays,
      subtext: highestPriorityBarangay
        ? `Highest: ${highestPriorityBarangay.barangay}`
        : 'No priority area',
    },
  ]

  const handleGenerateAnalyticsReport = () => {
    const generatedAtIso = new Date().toISOString()

    const csvRows = [
      ['Generated At', formatDateTime(generatedAtIso)],
      ['Generated By', 'Supervisor'],
      [],
      [`Operational Analytics Summary - ${barangayAnalytics.periodLabel}`],
      ['Metric', 'Value'],
      ...operationalStats.map((item) => [item.label, item.value]),
      [],
      [`Barangay Operational Analytics - ${barangayAnalytics.periodLabel}`],
      [
        'Barangay',
        'Submitted Reports',
        'Validated Incidents',
        'Priority Score',
        'Priority Level',
        'Average Severity',
        'Repeat Location',
        'Peak Time',
        'Available Personnel',
        'Required Personnel',
      ],
      ...barangayAnalytics.barangays.map((barangay) => [
        barangay.barangay,
        barangay.reportCount,
        barangay.validatedIncidentCount,
        barangay.priorityScore,
        barangay.priorityLevel,
        barangay.averageSeverity,
        barangay.topLocation || '-',
        barangay.peakTimeWindow || '-',
        barangay.availablePersonnel,
        barangay.requiredPersonnel,
      ]),
    ]

    const csvContent = csvRows
      .map((row) => (row.length === 0 ? '' : row.map(toCsvValue).join(',')))
      .join('\n')

    const blob = new Blob([csvContent], { type: 'text/csv;charset=utf-8;' })
    const url = URL.createObjectURL(blob)
    const downloadAnchor = document.createElement('a')
    const fileStamp = generatedAtIso.replace(/[-:TZ]/g, '').slice(0, 14)

    downloadAnchor.href = url
    downloadAnchor.download = `bantaycabagan-analytics-${fileStamp}.csv`
    document.body.appendChild(downloadAnchor)
    downloadAnchor.click()
    document.body.removeChild(downloadAnchor)
    window.setTimeout(() => URL.revokeObjectURL(url), 1000)
  }

  return (
    <div className="page-container fade-in p-3 p-md-4">
      <header className="page-header mb-4 reports-header">
        <div>
          <h2 className="page-title">Analytics</h2>
          <p className="page-subtitle">Patrol, incident, and barangay deployment trends</p>
        </div>
        <div className="analytics-page-actions">
          <div className="analytics-segmented-control" aria-label="Analytics period">
            {BARANGAY_ANALYTICS_PERIODS.map((option) => (
              <button
                key={option.value}
                type="button"
                className={barangayPeriod === option.value ? 'is-active' : ''}
                onClick={() => setBarangayPeriod(option.value)}
                aria-pressed={barangayPeriod === option.value}
              >
                {option.label}
              </button>
            ))}
          </div>
          <button type="button" className="report-generate-btn" onClick={handleGenerateAnalyticsReport}>
            Generate Report
          </button>
        </div>
      </header>

      <div className="stats-grid analytics-stats-grid row g-3 mb-3 mx-0">
        {operationalStats.map((stat) => (
          <div key={stat.label} className="col-12 col-sm-6 col-xl-3">
            <div className="stat-card slide-up h-100">
              <div className="stat-card__heading">
                <p className="stat-card__label">{stat.label}</p>
                {stat.isLive && (
                  <span className="stat-card__live" title="Synced from mobile resolve updates">
                    <span aria-hidden="true" />
                    Live
                  </span>
                )}
              </div>
              <strong className="stat-card__value">{stat.value}</strong>
              <p className="stat-card__subtext">{stat.subtext}</p>
            </div>
          </div>
        ))}
      </div>

      <BarangayOperationalAnalytics
        analytics={barangayAnalytics}
        period={barangayPeriod}
      />
    </div>
  )
}

export default AnalyticsPage
